### ISSUE TITLE
选择录取大学的算法究竟是什么

### ISSUE THREAD

**Issue by LWShowTime** [lingch16/UnivSimulator#8]
都是高考状元了，选了北大，上海和浙大，居然去了浙大...？

**Comment by lingch16** [comment]
（代码见main.js的370行左右）
玩家填报三个志愿。
按学校排名从高到低（无论玩家选择顺序如何），依次判断是否能被录取（有一定随机性。显示的高考成绩越好，被录取的概率越高，但不是绝对百分百）。
能被录取的学校里，将玩家录取到排名最高的学校。
由于文案描述和实际算法有区别，存在文案显示为省状元，但三个志愿全部落空的情况。


昨天晚上（v0.97版本更新）调整了录取大学的算法。省、市状元的情况，保底录取到第一、第二志愿。

如果是更早之前的版本，emmm，说明脸黑。（即前两次随机判断，均未达线，第三次随机判断达线）
v0.97之后的版本，理论上不存在这种情况。如果确定是v0.97之后版本出现的，说明有bug。。。

**Comment by LWShowTime** [comment]
回复真快，点赞开发更新速度。另外提个小建议，手机端的页面UI显示看不全，要上下滑动看状态值和决策选项，有点烦人，希望之后有优化方案。招个UI大佬吧

**Comment by HazukiKaguya** [comment]
> 回复真快，点赞开发更新速度。另外提个小建议，手机端的页面UI显示看不全，要上下滑动看状态值和决策选项，有点烦人，希望之后有优化方案。招个UI大佬吧

更新了状态栏的样式，现在它会浮动pin在顶部了（只在chromium系浏览器测试过效果），应该是优化了手机端的体验，可以在github page查看此更新是否解决你的这个问题，期待你的答复。
另：这种新需求建议开新的issue而不是在原有issue下提出。
